### ISSUE TITLE
I would like to know how the occlusion and low-resolution datasets used in Table 1 were set up. 

### ISSUE THREAD

**Issue by zqx951102** [LukeJaffe/GFN#10]
Hello, I would like to know how the occlusion and low-resolution datasets used in Table 1 were set up. Do I need to manually gather statistics from the original database, or is there a parameter setting during training that takes care of it? I look forward to your response. Thank you very much!

**Comment by LukeJaffe** [comment]
Thanks for your question. All you need to do is add the strings 'GOcclusion', 'GResolution' to your retrieval_name_list in the config (specific to the CUHK dataset). See configs/cuhk_test_final.yaml for an example. This assumes you have run the command which prepares these sets:
```
$ osr_prep_cuhk --dataset_dir ${DATASET_DIR}/cuhk
```

**Comment by zqx951102** [comment]
Hello, I would like to ask, if I am doing it based on SeqNet, how to set up the two data sets of Occlusion and Resolution in SeqNet?
