### ISSUE TITLE
Occlusion and Resolution 

### ISSUE THREAD

**Issue by zqx951102** [LukeJaffe/GFN#12]
Hello, I would like to ask, if I am doing it based on SeqNet, how to set up the two data sets of Occlusion and Resolution in SeqNet?

**Comment by zqx951102** [comment]
here I only find how to change the gallery_size, but I
don't know how to use the Occlusion and Resolution on CUHK dataset, Have you done research in this area, or can you give me some advice? Thank you very much for your help!
![141686813581_ pic](https://github.com/LukeJaffe/GFN/assets/41458957/2c05d0ec-8287-41c4-bfdf-c38c63fe7f51)
![101686813406_ pic](https://github.com/LukeJaffe/GFN/assets/41458957/0124aaa6-b9e3-4446-9bfb-03c8a909c1de)

**Comment by LukeJaffe** [comment]
In the original SeqNet paper and code, they do not appear to use those two sets. It looks like you could try to modify the "fname" and "protoc" variables to point to Occlusion.mat and Resolution.mat. If that doesn't work, you can also modify the hyperparameters of this codebase (SeqNeXt) to be close to the ones used for SeqNet, and use the utilities here for computing on those two sets.

**Comment by zqx951102** [comment]
Thank you very much for your reply, I found a stupid way to test the occlusion dataset. That is, modify the name to TestG100.mat.  you can see:
https://github.com/zqx951102/AMPN
