### ISSUE TITLE
dont know why

### ISSUE THREAD

**Issue by zqx951102** [LukeJaffe/GFN#13]
<img width="1040" alt="image" src="https://github.com/LukeJaffe/GFN/assets/41458957/24a58397-70ac-45a7-b653-9bdf9c50255a">
I'm not sure of the exact reason, but the program is not running anymore even after I've updated with pip install ray[tune]==1.13.0.

**Comment by LukeJaffe** [comment]
Can you see if you are able to run with debug=True? That will run without raytune.
