### ISSUE TITLE
Debug is true?

### ISSUE THREAD

**Issue by mly2784** [LukeJaffe/GFN#14]
Hello, I have changed debug to True to train GFN,  but I could not achieve the effect in the paper. The value of test_test_det_gfn_mAP is 0.487, and the value of test_test_det_gfn_top1 is 0.871. But the values for test_ap@0.5 and test_recall@0.5 are normal, at 0.9264 and 0.9512, respectively. What is the reason? Hoping for your reply.

**Comment by LukeJaffe** [comment]
When debug=True, the training script uses SequentialSampler, instead of RandomSampler, which is probably causing the gap in performance. Is there any reason to use debug=True? If you want to leave that, you can modify the code to use RandomSampler.

**Comment by mly2784** [comment]
Thanks for your reply! I'm trying the performance of runing without raytune, and I will try again according to what you said, thanks again for your guidance.
