### ISSUE TITLE
which indicators  should focus on?

### ISSUE THREAD

**Issue by zqx951102** [LukeJaffe/GFN#7]
Hello, I have tested your  code and tested it on the PRW dataset. I want to know which indicators I should focus on, namely, the Map and Top-1 that you refer to in your paper.
input: osr_run --trial_config=./configs/prw_test_final.yaml

`` 
(func pid=19147) ==> SUCCESS!!!                                                                                                
Result for WrappedDistributedTorchTrainable_cda35_00000:                                                                       
  date: 2023-03-22_21-59-16                                                                                                    
  done: true                                                                                                                   
  experiment_id: 56fe3ccccab14c33a1421bb441dc2be7                                                                              
  experiment_tag: '0'                                                                                                          
  hostname: user-virtual-machine                                                                                               
  iterations_since_restore: 1                                                                                                  
  node_ip: 10.60.150.135                                                                                                       
  pid: 18464                                                                                                                   
  test_ap@0.5: 0.934801125125824                                                                                               
  test_cross_cam_id_det_gfn_mAP: 0.5643779315391021                                                                            
  test_cross_cam_id_det_gfn_match: 1.0                                                                                         
  test_cross_cam_id_det_gfn_recall: 0.9788652820880083                                                                         
  test_cross_cam_id_det_gfn_top1: 0.8215848322800194                                                                           
  test_cross_cam_id_det_mAP: 0.5525456165277787                                                                                
  test_cross_cam_id_det_match: 1.0                                                                                             
  test_cross_cam_id_det_recall: 0.9788652820880083                                                                             
  test_cross_cam_id_det_top1: 0.8045697617890131                                                                               
  test_cross_cam_id_gt_gfn_mAP: 0.5782933392838289                                                                             
  test_cross_cam_id_gt_gfn_match: 1.0                                                                                          
  test_cross_cam_id_gt_gfn_recall: 1.0                                                                                         
  test_cross_cam_id_gt_gfn_top1: 0.8230432668935342                                                                            
  test_cross_cam_id_gt_mAP: 0.5664176155812705                                                                                 
  test_cross_cam_id_gt_match: 1.0                                                                                              
  test_cross_cam_id_gt_recall: 1.0                                                                                             
  test_cross_cam_id_gt_top1: 0.8045697617890131                                                                                
  test_cross_cam_id_image_gfn_frac_filter: 0.11711236787108889                                                                 
  test_cross_cam_id_image_gfn_mAP: 0.16209892104473658                                                                         
  test_cross_cam_id_image_gfn_thresh_filter: 0.4776982069015503                                                                
  test_cross_cam_id_image_gfn_top1: 0.42343218279047157                                                                        
  test_recall@0.5: 0.9568270688692043                                                                                          
  test_same_cam_id_det_gfn_mAP: 0.8505308214692695                                                                             
  test_same_cam_id_det_gfn_match: 1.0                                                                                          
  test_same_cam_id_det_gfn_recall: 0.9790137053352912                                                                          
  test_same_cam_id_det_gfn_top1: 0.9859017987360233  test_same_cam_id_gt_mAP: 0.8492902613364299
  test_same_cam_id_gt_match: 1.0
  test_same_cam_id_gt_recall: 1.0
  test_same_cam_id_gt_top1: 1.0
  test_same_cam_id_image_gfn_frac_filter: 0.2125033424679168
  test_same_cam_id_image_gfn_mAP: 0.6889602817530124
  test_same_cam_id_image_gfn_thresh_filter: 0.5215099453926086
  test_same_cam_id_image_gfn_top1: 1.0
  test_test_det_gfn_mAP: 0.5827848703489255
  test_test_det_gfn_match: 1.0
  test_test_det_gfn_recall: 0.9788257565934494
  test_test_det_gfn_top1: 0.924161400097229
  test_test_det_mAP: 0.5760174356415955
  test_test_det_match: 1.0
  test_test_det_recall: 0.9788257565934494
  test_test_det_top1: 0.8945065629557608
  test_test_gt_gfn_mAP: 0.5990268233035214
  test_test_gt_gfn_match: 1.0
  test_test_gt_gfn_recall: 1.0
  test_test_gt_gfn_top1: 0.9309674282936315
  test_test_gt_mAP: 0.5917157777048339
  test_test_gt_match: 1.0
  test_test_gt_recall: 1.0
  test_test_gt_top1: 0.8998541565386485
  test_test_image_gfn_frac_filter: 0.11459317284876058
  test_test_image_gfn_mAP: 0.20687682098861937
  test_test_image_gfn_thresh_filter: 0.4808691143989563
  test_test_image_gfn_top1: 0.7841516771998055
  time_since_restore: 8954.510276317596
  time_this_iter_s: 8954.510276317596
  time_total_s: 8954.510276317596
  timestamp: 1679493556
  timesteps_since_restore: 0
  training_iteration: 1
  trial_id: cda35_00000
  warmup_time: 16.191797971725464

== Status ==
Current time: 2023-03-22 21:59:20 (running for 02:29:53.97)
Memory usage on this node: 10.7/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/2 GPUs, 0.0/34.04 GiB heap, 0.0/17.02 GiB objects (0.0/1.0 accelerator_type:V100)
Result logdir: /diskvdb/yyl/zqx_PS/paper/GFN-main/logging/prw_final
Number of trials: 1/1 (1 TERMINATED)
+----------------------------------------------+------------+---------------------+--------+------------------+---------------+-------------------+----------------------+
| Trial name                                   | status     | loc                 |   iter |   total time (s) |   test_ap@0.5 |   test_recall@0.5 |   test_test_gt_match |
|----------------------------------------------+------------+---------------------+--------+------------------+---------------+-------------------+----------------------|
| WrappedDistributedTorchTrainable_cda35_00000 | TERMINATED | 10.60.150.135:18464 |      1 |          8954.51 |      0.934801 |          0.956827 |                    1 |
+----------------------------------------------+------------+---------------------+--------+------------------+---------------+-------------------+----------------------+

2023-03-22 21:59:20,951 INFO tune.py:702 -- Total run time: 8994.12 seconds (8993.95 seconds for the tuning loop).

**Comment by LukeJaffe** [comment]
Good question, sorry this is not more clear! The metrics in Table 2 in the paper (for the PRW dataset) are given by the keys, "test_test_det_mAP", "test_test_det_top1", "test_test_det_gfn_mAP", "test_test_det_gfn_top1".

More generally, the format for metrics is {protocol.partition_name}_{protocol.name}_{source_name}{gfn_name}_{metric}.
- protocol.partition_name is the name of the partition e.g., train/val/test
- protocol.name is the name of the subset of that partition used for the metric. For PRW, this could be e.g., same_cam or cross_cam indicating whether whether the query and gallery samples came from the same camera. When it is just test that is the full standard test partition for PRW.
- source_name is "det" indicating detected boxes, or "gt" indicating ground truth boxes (equivalent to the "perfect" detector).
- gfn_name indicates whether or not GFN scores where used for that retrieval metric (multiplied by re-id scores), this is either "" or "gfn"
- and metric is the metric name: top1, mAP are the standard retrieval metrics.
- metrics with "image" in the name are measured at the scene level using only GFN scores for the query and gallery scenes (and no boxes, ground truth or detected).

And then there are several other bonus metrics not described in the paper, mostly for diagnostic purposes.

Let me know if there are any other questions about metrics.

**Comment by zqx951102** [comment]
Thank you very much for your response. It was very helpful to me, and your explanation has made the metric names much clearer. If I have any further questions, I will definitely ask you. Have a great day!
